/**
 * Copyright 2026 Jordan Nzokou and Doeg Tiozang
 * Project: Nexvantis
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

`timescale 1ns/1ps
`default_nettype none

/**
 * Module: Data_Memory
 *  *
 *  * Behavioral word memory with synchronous stores and asynchronous loads.
 *  * Address bits [1:0] are removed because the implemented LW/SW subset performs
 *  * aligned 32-bit accesses only. The array is zero-initialized at simulation
 *  * start; rst_n gates writes and forces the observable read output to zero.
 *  *
 *  * Byte enables, misalignment exceptions, and external bus timing are outside
 *  * this module's intentionally limited contract.
 */

// -----------------------------------------------------------------------------
// DETAILED ENGINEERING COMMENTARY
//
// Access model:
//   Reads are asynchronous and stores are synchronous. A store captures WD into
//   the word selected by A[9:2] only when WE is asserted at a rising edge.
//
// Address interpretation:
//   A carries a byte address generated by the ALU. Dropping bits [1:0] converts
//   aligned byte addresses 0,4,8,... into word indices 0,1,2,... .
//
// Reset/modeling note:
//   Full-array reset creates deterministic tests. It is not a claim that every
//   target RAM primitive supports synchronous clearing of all words.
//
// Scope:
//   There are no byte enables, access-size controls, latency, handshake, or
//   misalignment checks in this memory model.
// -----------------------------------------------------------------------------
// Word-addressable data memory with synchronous writes and asynchronous reads.
// External addresses are expressed in bytes and converted to word indices.
module Data_Memory #(
    parameter DEPTH      = 256,
    parameter ADDR_WIDTH = 8
)(
    input  wire        clk,
    input  wire        rst_n,
    input  wire        WE,
    input  wire [31:0] A,
    input  wire [31:0] WD,
    output wire [31:0] RD
);

    // Behavioral word array addressed by A[ADDR_WIDTH+1:2].
    reg [31:0] mem [0:DEPTH-1];
    integer i;

    // Deterministic simulation initialization.
    initial begin
        for (i = 0; i < DEPTH; i = i + 1)
            mem[i] = 32'b0;
    end

    // Store commits on the rising edge only when both rst_n and WE are high.
    always @(posedge clk) begin
        if (rst_n && WE)
            mem[A[ADDR_WIDTH+1:2]] <= WD;
    end

    // Load data is visible asynchronously from the selected aligned word.
    assign RD = (!rst_n) ? 32'b0 : mem[A[ADDR_WIDTH+1:2]];

endmodule

`default_nettype wire
